name: Submap
settings:
  DEVELOPMENT_TEAM: K78G42H4U2
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 0.0.1
options:
  bundleIdPrefix: com.joeblau
  deploymentTarget:
    iOS: "17.5"
  createIntermediateGroups: true
  preGenCommand: .github/scripts/pre.sh
  postGenCommand: .github/scripts/post.sh
schemes:
  Submap:
    build:
      targets:
        Submap: all
    run:
      environmentVariables:
        IDEPreferLogStreaming: YES
packages:
  openai:
    url: https://github.com/MacPaw/OpenAI.git
    from: 0.2.9
targets:
  Submap:
    type: application
    platform: iOS
    sources:
      - path: Apps/iOS
        excludes:
          - Apps/iOS/PreviewContent/*
      - path: Apps/iOS/Resources/
        buildPhase: resources
      - path: .
        includes:
          - .env
        buildPhase: resources
    settings:
      DEVELOPMENT_ASSET_PATHS: Apps/iOS/PreviewContent
      PRODUCT_BUNDLE_IDENTIFIER: com.joeblau.Submap
      SUPPORTED_PLATFORMS: [iphoneos, iphonesimulator]
      TARGETED_DEVICE_FAMILY: 1
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      GENERATE_INFOPLIST_FILE: true
      VALIDATE_WORKSPACE: true
    dependencies:
      - package: openai
        product: OpenAI
  UnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/Unit
  UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/UI